// Automatisch erzeugt aus regeln.json. Nicht von Hand aendern: lerner.py neu laufen lassen
// und gen_regeln_cs.py aufrufen. Gelernt an Dingden gegen den NEPLAN-Export derselben Datei.
//
// Arten: v/h  Wert ab Ende des k-ten Texts vom Objektanfang (v) bzw. vor dem Namen (h)
//        ve/he Wert ab Anfang des Texts k+1, also vom Blockende aus gezaehlt
//        tv/th Text an Stelle k (vom Anfang bzw. vor dem Namen)
//        ab    Kabelabschnitt: Wert ab Ende des Abschnittstexts k (0 Typ, 1 leer, 2 Materialnr.)
//        abt   Kabelabschnitt: der Abschnittstext k selbst
//        null  in Dingden immer 0     leer  in Dingden immer leer
// Formate: d Double, f Single, i Int32, h Int16, b Byte

namespace NeplanLeser
{
    public static class Regeln
    {
        public static readonly Regel[] Spalten = new Regel[]
        {
            new Regel("BUSBAR", "TYPE", "leer"),
            new Regel("BUSBAR", "DESCRIPTION", "th", -9),
            new Regel("BUSBAR", "PROJECTED", "null"),
            new Regel("BUSBAR", "NODETYPE", "he", -30, -112, 'i'),
            new Regel("BUSBAR", "UN", "he", -30, -108, 'd'),
            new Regel("BUSBAR", "FN", "he", -30, -100, 'd'),
            new Regel("BUSBAR", "UMIN", "he", -30, -92, 'd'),
            new Regel("BUSBAR", "UMAX", "he", -30, -84, 'd'),
            new Regel("BUSBAR", "IPMAX", "null"),
            new Regel("BUSBAR", "USOLL", "he", -30, -68, 'd'),
            new Regel("BUSBAR", "IR", "null"),
            new Regel("BUSBAR", "TFEED", "null"),
            new Regel("BUSBAR", "KNOTRED", "null"),
            new Regel("BUSBAR", "DISTPROTNODE", "null"),
            new Regel("BUSBAR", "EMTNODE", "null"),
            new Regel("BUSBAR", "HYPERLINK", "th", -3),
            new Regel("BUSBAR", "MAINTENANCE", "null"),
            new Regel("BUSBAR", "InStationType", "null"),
            new Regel("BUSBAR", "ReliabilityIdeal", "null"),
            new Regel("BUSBAR", "RelFailureGroup", "null"),
            new Regel("BUSBAR", "ProtType", "null"),
            new Regel("BUSBAR", "TManual", "null"),
            new Regel("BUSBAR", "UseDefaultTManual", "h", -1, 16, 'b'),
            new Regel("BUSBAR", "RelTypeBusbar", "leer"),
            new Regel("BUSBAR", "RelTypeCircBrk", "leer"),
            new Regel("BUSBAR", "RelTypeDisc", "leer"),
            new Regel("BUSBAR", "SwBayCfgDef", "null"),
            new Regel("BUSBAR", "SwBayRemOpDef", "null"),
            new Regel("BUSBAR", "SwBayUseDefault", "h", -1, 16, 'b'),
            new Regel("BUSBAR", "TAccess", "null"),
            new Regel("BUSBAR", "UseDefaultTAccess", "h", -1, 16, 'b'),
            new Regel("BUSBAR", "SCIndicator", "null"),
            new Regel("BUSBAR", "TTrip", "null"),
            new Regel("BUSBAR", "ALIASNAME", "th", -2),
            new Regel("BUSBAR", "Equipment", "null"),
            new Regel("BUSBAR", "Gap", "v", 4, 4, 'd'),
            new Regel("BUSBAR", "legacy", "th", -3),
            new Regel("BUSBAR", "panelname", "tv", 24),   // 155/163
            new Regel("LOAD", "TYPE", "th", -6),
            new Regel("LOAD", "DESCRIPTION", "th", -5),
            new Regel("LOAD", "PROJECTED", "null"),
            new Regel("LOAD", "S", "ve", 0, -192, 'd'),
            new Regel("LOAD", "P", "ve", 0, -184, 'd'),
            new Regel("LOAD", "Q", "ve", 0, -176, 'd'),
            new Regel("LOAD", "I", "ve", 0, -168, 'd'),
            new Regel("LOAD", "COS", "ve", 0, -160, 'd'),
            new Regel("LOAD", "LFTYPE", "ve", 0, -152, 'h'),
            new Regel("LOAD", "UNIT", "ve", 0, -148, 'i'),
            new Regel("LOAD", "DOMUNITS", "null"),
            new Regel("LOAD", "XP", "leer"),
            new Regel("LOAD", "XQ", "leer"),
            new Regel("LOAD", "P0", "null"),
            new Regel("LOAD", "Q0", "null"),
            new Regel("LOAD", "FAKVARIABLE", "h", -1, 16, 'b'),
            new Regel("LOAD", "SIMFAK_LB", "ve", 0, -12, 'd'),
            new Regel("LOAD", "SIMFAKQ_LB", "ve", 0, -12, 'd'),
            new Regel("LOAD", "E", "null"),
            new Regel("LOAD", "K1VEL", "null"),
            new Regel("LOAD", "K2VEL", "null"),
            new Regel("LOAD", "LFCONSTP", "null"),
            new Regel("LOAD", "VOLTDEP", "null"),
            new Regel("LOAD", "EQUIHA", "null"),
            new Regel("LOAD", "BLIP", "leer"),
            new Regel("LOAD", "BLIQ", "leer"),
            new Regel("LOAD", "BLPP", "leer"),
            new Regel("LOAD", "BLPQ", "leer"),
            new Regel("LOAD", "BLFP", "leer"),
            new Regel("LOAD", "BLFQ", "leer"),
            new Regel("LOAD", "UA1", "ve", 0, -68, 'd'),
            new Regel("LOAD", "UA2", "ve", 0, -52, 'd'),
            new Regel("LOAD", "UB1", "ve", 0, -32, 'd'),
            new Regel("LOAD", "UB2", "ve", 0, -24, 'd'),
            new Regel("LOAD", "DEATHBAND", "null"),
            new Regel("LOAD", "UBMIN", "ve", 0, -32, 'd'),
            new Regel("LOAD", "UBMAX", "ve", 0, -24, 'd'),
            new Regel("LOAD", "REFYEAR", "null"),
            new Regel("LOAD", "FREQDEP", "leer"),
            new Regel("LOAD", "DYNMODEL", "null"),
            new Regel("LOAD", "TLAGP", "leer"),
            new Regel("LOAD", "TLAGQ", "leer"),
            new Regel("LOAD", "XP_DYN", "leer"),
            new Regel("LOAD", "XQ_DYN", "leer"),
            new Regel("LOAD", "BLIP_DYN", "leer"),
            new Regel("LOAD", "BLIQ_DYN", "leer"),
            new Regel("LOAD", "BLPP_DYN", "leer"),
            new Regel("LOAD", "BLPQ_DYN", "leer"),
            new Regel("LOAD", "BLFP_DYN", "leer"),
            new Regel("LOAD", "BLFQ_DYN", "leer"),
            new Regel("LOAD", "PPORT_DYN", "leer"),
            new Regel("LOAD", "QPORT_DYN", "leer"),
            new Regel("LOAD", "PHASE", "null"),
            new Regel("LOAD", "HYPERLINK", "leer"),
            new Regel("LOAD", "MAINTENANCE", "null"),
            new Regel("LOAD", "GND_CONNECT", "null"),
            new Regel("LOAD", "NUMCUST", "null"),
            new Regel("LOAD", "ALIASNAME", "th", -2),
            new Regel("LOAD", "PSTATIC", "v", 5, 68, 'd'),
            new Regel("LOAD", "QSTATIC", "v", 5, 68, 'd'),
            new Regel("LOAD", "A0P_Lf", "null"),
            new Regel("LOAD", "A1P_Lf", "null"),
            new Regel("LOAD", "A2P_Lf", "null"),
            new Regel("LOAD", "A0Q_Lf", "null"),
            new Regel("LOAD", "A1Q_Lf", "null"),
            new Regel("LOAD", "A2Q_Lf", "null"),
            new Regel("LOAD", "N0P_Lf", "null"),
            new Regel("LOAD", "N1P_Lf", "null"),
            new Regel("LOAD", "N2P_Lf", "null"),
            new Regel("LOAD", "N0Q_Lf", "null"),
            new Regel("LOAD", "N1Q_Lf", "null"),
            new Regel("LOAD", "N2Q_Lf", "null"),
            new Regel("LOAD", "A0P_Dyn", "null"),
            new Regel("LOAD", "A1P_Dyn", "null"),
            new Regel("LOAD", "A2P_Dyn", "v", 5, 68, 'd'),
            new Regel("LOAD", "A0Q_Dyn", "null"),
            new Regel("LOAD", "A1Q_Dyn", "null"),
            new Regel("LOAD", "A2Q_Dyn", "v", 5, 68, 'd'),
            new Regel("LOAD", "N0P_Dyn", "null"),
            new Regel("LOAD", "N1P_Dyn", "null"),
            new Regel("LOAD", "N2P_Dyn", "ve", 2, -48, 'd'),
            new Regel("LOAD", "N0Q_Dyn", "null"),
            new Regel("LOAD", "N1Q_Dyn", "null"),
            new Regel("LOAD", "N2Q_Dyn", "ve", 2, -48, 'd'),
            new Regel("LOAD", "CFP", "null"),
            new Regel("LOAD", "CFQ", "null"),
            new Regel("LOAD", "TP", "null"),
            new Regel("LOAD", "TQ", "null"),
            new Regel("LOAD", "TV", "ve", 2, -96, 'd'),
            new Regel("LOAD", "TF", "ve", 2, -96, 'd'),
            new Regel("AC_GENERIC_COMP", "TYPE", "leer"),
            new Regel("AC_GENERIC_COMP", "ALIASNAME", "tv", 16),
            new Regel("AC_GENERIC_COMP", "DESCRIPTION", "leer"),
            new Regel("AC_GENERIC_COMP", "PROJECTED", "null"),
            new Regel("AC_GENERIC_COMP", "MAINTENANCE", "null"),
            new Regel("AC_GENERIC_COMP", "UR", "v", 17, 28, 'b'),
            new Regel("AC_GENERIC_COMP", "SR", "ve", 0, -130, 'd'),
            new Regel("AC_GENERIC_COMP", "COSR", "he", -18, -114, 'd'),
            new Regel("AC_GENERIC_COMP", "GENTYPE", "he", -18, -82, 'h'),
            new Regel("AC_GENERIC_COMP", "SK2MAX", "ve", 0, -58, 'd'),
            new Regel("AC_GENERIC_COMP", "SK2MIN", "null"),
            new Regel("AC_GENERIC_COMP", "R1TOX1MAX", "null"),
            new Regel("AC_GENERIC_COMP", "R1TOX1MIN", "null"),
            new Regel("AC_GENERIC_COMP", "ISOLATED", "null"),
            new Regel("AC_GENERIC_COMP", "REVERSE", "null"),
            new Regel("AC_GENERIC_COMP", "CONDRIVE", "null"),
            new Regel("AC_GENERIC_COMP", "SSET", "null"),
            new Regel("AC_GENERIC_COMP", "PSET", "he", -18, -166, 'd'),
            new Regel("AC_GENERIC_COMP", "QSET", "v", 0, 36, 'd'),
            new Regel("AC_GENERIC_COMP", "ISET", "null"),
            new Regel("AC_GENERIC_COMP", "COSSET", "null"),
            new Regel("AC_GENERIC_COMP", "USET", "null"),
            new Regel("AC_GENERIC_COMP", "UASET", "null"),
            new Regel("AC_GENERIC_COMP", "UNIT", "null"),
            new Regel("AC_GENERIC_COMP", "HARMSOURCE", "null"),
            new Regel("AC_GENERIC_COMP", "FAKVARIABLE", "null"),
            new Regel("AC_GENERIC_COMP", "SIMFAK_LB", "he", -13, -4, 'h'),
            new Regel("AC_GENERIC_COMP", "SIMFAKQ_LB", "he", -13, -4, 'h'),
            new Regel("AC_GENERIC_COMP", "LFTYPE", "h", -8, 4, 'i'),
            new Regel("AC_GENERIC_COMP", "CAPACITIVE", "null"),
            new Regel("AC_GENERIC_COMP", "Z0TOZ1MAX", "null"),
            new Regel("AC_GENERIC_COMP", "R0TOX0MAX", "null"),
            new Regel("AC_GENERIC_COMP", "Z2TOZ1MAX", "null"),
            new Regel("AC_GENERIC_COMP", "R2TOX2MAX", "null"),
            new Regel("AC_GENERIC_COMP", "PUCTRLACTIVE", "null"),
            new Regel("AC_GENERIC_COMP", "PUCTRLUKNEE", "null"),
            new Regel("AC_GENERIC_COMP", "PUCTRLULIMIT", "null"),
            new Regel("AC_GENERIC_COMP", "IECPS_Type", "null"),
            new Regel("AC_GENERIC_COMP", "KappaWD", "null"),
            new Regel("AC_GENERIC_COMP", "iWDmax", "null"),
            new Regel("AC_GENERIC_COMP", "IkWDmax", "null"),
            new Regel("AC_GENERIC_COMP", "IkWDmin", "null"),
            new Regel("AC_GENERIC_COMP", "RzuXWD", "null"),
            new Regel("AC_GENERIC_COMP", "ISkPF3p", "null"),
            new Regel("AC_GENERIC_COMP", "ISkPF2p", "null"),
            new Regel("AC_GENERIC_COMP", "ISkPF2pE", "null"),
            new Regel("AC_GENERIC_COMP", "ISkPF1p", "null"),
            new Regel("AC_GENERIC_COMP", "IkPFmax", "null"),
            new Regel("AC_GENERIC_COMP", "IkPFmin", "null"),
            new Regel("AC_GENERIC_COMP", "UrTHV", "null"),
            new Regel("AC_GENERIC_COMP", "TakeUrTHV", "null"),
            new Regel("AC_GENERIC_COMP", "HYPERLINK", "null"),
            new Regel("AC_GENERIC_COMP", "tabend", "leer"),
            new Regel("AC_GENERIC_COMP", "PAVE", "leer"),
            new Regel("DISC_SWITCH", "TYPE", "tv", 2),
            new Regel("DISC_SWITCH", "ALIASNAME", "leer"),   // 0/51
            new Regel("DISC_SWITCH", "DESCRIPTION", "tv", 3),
            new Regel("DISC_SWITCH", "PROJECTED", "null"),
            new Regel("DISC_SWITCH", "MAINTENANCE", "null"),
            new Regel("DISC_SWITCH", "UR", "null"),
            new Regel("DISC_SWITCH", "IR", "null"),
            new Regel("DISC_SWITCH", "IK2MAX", "null"),
            new Regel("DISC_SWITCH", "IBMAX", "null"),
            new Regel("DISC_SWITCH", "IPMAX", "null"),
            new Regel("DISC_SWITCH", "REMOTE", "null"),
            new Regel("DISC_SWITCH", "PHASE", "null"),
            new Regel("DISC_SWITCH", "REIDEAL", "leer"),
            new Regel("DISC_SWITCH", "RETYPE", "leer"),
            new Regel("DISC_SWITCH", "HYPERLINK", "leer"),
            new Regel("LOAD_SWITCH", "TYPE", "tv", 4),
            new Regel("LOAD_SWITCH", "DESCRIPTION", "tv", 5),
            new Regel("LOAD_SWITCH", "PROJECTED", "null"),
            new Regel("LOAD_SWITCH", "UR", "null"),
            new Regel("LOAD_SWITCH", "IR", "null"),
            new Regel("LOAD_SWITCH", "IK2MAX", "null"),
            new Regel("LOAD_SWITCH", "IBMAX", "null"),
            new Regel("LOAD_SWITCH", "IPMAX", "null"),
            new Regel("LOAD_SWITCH", "REMOTE", "null"),
            new Regel("LOAD_SWITCH", "PHASE", "null"),
            new Regel("LOAD_SWITCH", "HYPERLINK", "leer"),
            new Regel("LOAD_SWITCH", "MAINTENANCE", "null"),
            new Regel("LOAD_SWITCH", "ALIASNAME", "leer"),
            new Regel("CIRC_BREAK", "TYPE", "leer"),
            new Regel("CIRC_BREAK", "DESCRIPTION", "tv", 3),
            new Regel("CIRC_BREAK", "PROJECTED", "null"),
            new Regel("CIRC_BREAK", "UR", "null"),
            new Regel("CIRC_BREAK", "IR", "null"),
            new Regel("CIRC_BREAK", "IK2MAX", "null"),
            new Regel("CIRC_BREAK", "IBMAX", "null"),
            new Regel("CIRC_BREAK", "IPMAX", "null"),
            new Regel("CIRC_BREAK", "REMOTE", "null"),
            new Regel("CIRC_BREAK", "KFACTOR", "null"),
            new Regel("CIRC_BREAK", "CYCLES", "ve", 0, -68, 'h'),
            new Regel("CIRC_BREAK", "COSTEST", "null"),
            new Regel("CIRC_BREAK", "VOLTAGE", "h", -8, 0, 'h'),
            new Regel("CIRC_BREAK", "STANDARD", "null"),
            new Regel("CIRC_BREAK", "PHASE", "null"),
            new Regel("CIRC_BREAK", "MINIATURE", "null"),
            new Regel("CIRC_BREAK", "HYPERLINK", "leer"),
            new Regel("CIRC_BREAK", "MAINTENANCE", "null"),
            new Regel("CIRC_BREAK", "ALIASNAME", "leer"),
            new Regel("CIRC_BREAK", "REIDEAL", "leer"),
            new Regel("CIRC_BREAK", "RETYPE", "leer"),
            new Regel("TRAFO2", "TYPE", "leer"),
            new Regel("TRAFO2", "DESCRIPTION", "tv", 117),
            new Regel("TRAFO2", "PROJECTED", "null"),
            new Regel("TRAFO2", "VECGROUP", "tv", 1),
            new Regel("TRAFO2", "PSTRAFO", "null"),
            new Regel("TRAFO2", "UR1", "ve", 1, -172, 'd'),
            new Regel("TRAFO2", "UR2", "he", -7, 20, 'b'),
            new Regel("TRAFO2", "UKR", "ve", 1, -156, 'd'),
            new Regel("TRAFO2", "UKR0", "null"),
            new Regel("TRAFO2", "URR", "he", -122, -140, 'd'),
            new Regel("TRAFO2", "URR0", "null"),
            new Regel("TRAFO2", "RE1", "null"),
            new Regel("TRAFO2", "XE1", "null"),
            new Regel("TRAFO2", "ZE1ACTIVE", "v", 5, 58, 'h'),
            new Regel("TRAFO2", "EARTHTYPE1", "null"),
            new Regel("TRAFO2", "RE2", "null"),
            new Regel("TRAFO2", "XE2", "null"),
            new Regel("TRAFO2", "ZE2ACTIVE", "v", 5, 58, 'h'),
            new Regel("TRAFO2", "EARTHTYPE2", "null"),
            new Regel("TRAFO2", "I0", "null"),
            new Regel("TRAFO2", "PFE", "null"),
            new Regel("TRAFO2", "SR", "v", 1, 124, 'd'),
            new Regel("TRAFO2", "REGULATED", "null"),
            new Regel("TRAFO2", "TAPSIDE", "h", -6, 22, 'b'),
            new Regel("TRAFO2", "CNTRLSIDE", "h", -6, 22, 'b'),
            new Regel("TRAFO2", "BETAU", "null"),
            new Regel("TRAFO2", "DELTAU", "ve", 1, -24, 'd'),
            new Regel("TRAFO2", "TAPMIN", "h", -6, 22, 'b'),
            new Regel("TRAFO2", "TAPR", "h", -8, 0, 'h'),
            new Regel("TRAFO2", "TAPMAX", "v", 119, 16, 'h'),
            new Regel("TRAFO2", "TAPACT", "h", -8, 0, 'h'),
            new Regel("TRAFO2", "FREDEP", "leer"),
            new Regel("TRAFO2", "USET", "he", -121, -480, 'd'),
            new Regel("TRAFO2", "PSET", "null"),
            new Regel("TRAFO2", "TNUK", "null"),
            new Regel("TRAFO2", "TNUK0", "null"),
            new Regel("TRAFO2", "TXUK", "null"),
            new Regel("TRAFO2", "TXUK0", "null"),
            new Regel("TRAFO2", "IR1MIN", "null"),
            new Regel("TRAFO2", "IR1MAX", "null"),
            new Regel("TRAFO2", "IR2MIN", "null"),
            new Regel("TRAFO2", "IR2MAX", "null"),
            new Regel("TRAFO2", "SRMIN", "he", -7, 20, 'b'),
            new Regel("TRAFO2", "SRMAX", "he", -7, 20, 'b'),
            new Regel("TRAFO2", "EVALUATION", "h", -6, 22, 'b'),
            new Regel("TRAFO2", "UK010", "null"),
            new Regel("TRAFO2", "UK020", "null"),
            new Regel("TRAFO2", "COMPOUND", "null"),
            new Regel("TRAFO2", "IMINCOMP", "null"),
            new Regel("TRAFO2", "IMAXCOMP", "null"),
            new Regel("TRAFO2", "UMINCOMP", "null"),
            new Regel("TRAFO2", "UMAXCOMP", "null"),
            new Regel("TRAFO2", "COMPWINDING", "null"),
            new Regel("TRAFO2", "SWITCHABLE", "null"),
            new Regel("TRAFO2", "OPERVALUE", "null"),
            new Regel("TRAFO2", "UBMAX", "null"),
            new Regel("TRAFO2", "IBMAX", "null"),
            new Regel("TRAFO2", "COSB", "null"),
            new Regel("TRAFO2", "UBMIN", "null"),
            new Regel("TRAFO2", "PTAP", "null"),
            new Regel("TRAFO2", "HYPERLINK", "leer"),
            new Regel("TRAFO2", "MAINTENANCE", "null"),
            new Regel("TRAFO2", "ALIASNAME", "leer"),
            new Regel("TRAFO2", "IR1MID", "null"),
            new Regel("TRAFO2", "IR2MID", "null"),
            new Regel("TRAFO2", "SRMID", "null"),
            new Regel("TRAFO2", "COMMONEARTHING", "null"),
            new Regel("TRAFO2", "AUTOTRANSFORMER", "null"),
            new Regel("TRAFO2", "USEEARTHINGCOMPONENT", "null"),
            new Regel("TRAFO2", "USEEARTHINGCOMPONENT_SIDE", "null"),
            new Regel("TRAFO2", "ZIMPLIMITFORMODEL", "v", 5, 58, 'h'),
            new Regel("TRAFO2", "REIDEAL", "null"),
            new Regel("TRAFO2", "RETYPE", "leer"),
            new Regel("TRAFO2", "TAPCHANGER2ACTIV", "null"),
            new Regel("TRAFO2", "TAPSIDE2", "null"),
            new Regel("TRAFO2", "BETAU2", "v", 2, 388, 'd'),
            new Regel("TRAFO2", "DELTAU2", "null"),
            new Regel("TRAFO2", "TAPMIN2", "null"),
            new Regel("TRAFO2", "TAPR2", "null"),
            new Regel("TRAFO2", "TAPMAX2", "null"),
            new Regel("TRAFO2", "TAPACT2", "null"),
            new Regel("TRAFO2", "UQGERACTIV", "null"),
            new Regel("TRAFO2", "QSET", "null"),
            new Regel("TRAFO2", "CONSRATIOPHASEVARIATION", "null"),
            new Regel("TRAFO2", "CONSIMPEDANCEVARIATION", "null"),
            new Regel("TRAFO2", "SYMMREG_UCTE", "null"),
            new Regel("TRAFO2", "SYMMPHASESHIFT_UCTE", "null"),
            new Regel("TRAFO2", "REGNODE", "ve", 2, -386, 'h'),
            new Regel("TRAFO2", "3SinglePhaseTrafo", "null"),
            new Regel("TRAFO2", "Ur1_L1", "null"),
            new Regel("TRAFO2", "Ur2_L1", "null"),
            new Regel("TRAFO2", "Uk_L1", "null"),
            new Regel("TRAFO2", "Vcu_L1", "null"),
            new Regel("TRAFO2", "Sr_L1", "null"),
            new Regel("TRAFO2", "Uk0_L1", "null"),
            new Regel("TRAFO2", "Vcu0_L1", "null"),
            new Regel("TRAFO2", "I0_L1", "leer"),
            new Regel("TRAFO2", "PFe_L1", "leer"),
            new Regel("TRAFO2", "Ur1_L2", "null"),
            new Regel("TRAFO2", "Ur2_L2", "null"),
            new Regel("TRAFO2", "Uk_L2", "null"),
            new Regel("TRAFO2", "Vcu_L2", "null"),
            new Regel("TRAFO2", "Sr_L2", "null"),
            new Regel("TRAFO2", "Uk0_L2", "null"),
            new Regel("TRAFO2", "Vcu0_L2", "null"),
            new Regel("TRAFO2", "I0_L2", "leer"),
            new Regel("TRAFO2", "PFe_L2", "leer"),
            new Regel("TRAFO2", "Ur1_L3", "null"),
            new Regel("TRAFO2", "Ur2_L3", "null"),
            new Regel("TRAFO2", "Uk_L3", "null"),
            new Regel("TRAFO2", "Vcu_L3", "null"),
            new Regel("TRAFO2", "Sr_L3", "null"),
            new Regel("TRAFO2", "Uk0_L3", "null"),
            new Regel("TRAFO2", "Vcu0_L3", "null"),
            new Regel("TRAFO2", "I0_L3", "leer"),
            new Regel("TRAFO2", "PFe_L3", "leer"),
            new Regel("NETWFEEDER", "TYPE", "leer"),
            new Regel("NETWFEEDER", "DESCRIPTION", "leer"),
            new Regel("NETWFEEDER", "PROJECTED", "null"),
            new Regel("NETWFEEDER", "SK2MAX", "ve", 0, -180, 'd'),
            new Regel("NETWFEEDER", "SK2MIN", "ve", 0, -172, 'd'),
            new Regel("NETWFEEDER", "IK2MAX", "ve", 0, -164, 'd'),
            new Regel("NETWFEEDER", "IK2MIN", "ve", 0, -156, 'd'),
            new Regel("NETWFEEDER", "IEC", "he", -3, -14, 'h'),
            new Regel("NETWFEEDER", "EOPER", "he", -3, -14, 'h'),
            new Regel("NETWFEEDER", "Z0TOZ1MAX", "null"),
            new Regel("NETWFEEDER", "Z0TOZ1MIN", "null"),
            new Regel("NETWFEEDER", "R1TOX1MAX", "he", -12, -132, 'd'),
            new Regel("NETWFEEDER", "R1TOX1MIN", "null"),
            new Regel("NETWFEEDER", "R0TOX0MAX", "null"),
            new Regel("NETWFEEDER", "R0TOX0MIN", "null"),
            new Regel("NETWFEEDER", "C1", "null"),
            new Regel("NETWFEEDER", "UOPER", "he", -12, -108, 'd'),
            new Regel("NETWFEEDER", "AUOPER", "null"),
            new Regel("NETWFEEDER", "POPER", "he", -12, -92, 'd'),
            new Regel("NETWFEEDER", "QOPER", "he", -12, -84, 'd'),
            new Regel("NETWFEEDER", "SLPORTION", "null"),
            new Regel("NETWFEEDER", "LFTYPE", "null"),
            new Regel("NETWFEEDER", "FREQDEP", "leer"),
            new Regel("NETWFEEDER", "FCOST1", "null"),
            new Regel("NETWFEEDER", "FCOST2", "null"),
            new Regel("NETWFEEDER", "FCOST3", "null"),
            new Regel("NETWFEEDER", "COSTMULT", "he", -3, -14, 'h'),
            new Regel("NETWFEEDER", "HYPERLINK", "leer"),
            new Regel("NETWFEEDER", "MAINTENANCE", "null"),
            new Regel("NETWFEEDER", "ALIASNAME", "tv", 10),
            new Regel("NETWFEEDER", "REIDEAL", "null"),
            new Regel("NETWFEEDER", "RETYPE", "leer"),
            new Regel("NETWFEEDER", "REGNODE", "he", -12, -4, 'h'),
            new Regel("NETWFEEDER", "REGNODE_NAME", "leer"),
            new Regel("BB_COUPLER", "TYPE", "leer"),
            new Regel("BB_COUPLER", "DESCRIPTION", "tv", 5),
            new Regel("BB_COUPLER", "PROJECTED", "null"),
            new Regel("BB_COUPLER", "IR", "null"),
            new Regel("BB_COUPLER", "IPMAX", "null"),
            new Regel("BB_COUPLER", "R1", "h", -10, 34, 'd'),
            new Regel("BB_COUPLER", "X1", "h", -10, 34, 'd'),
            new Regel("BB_COUPLER", "R0", "h", -10, 34, 'd'),
            new Regel("BB_COUPLER", "X0", "h", -10, 34, 'd'),
            new Regel("BB_COUPLER", "TLT", "null"),
            new Regel("BB_COUPLER", "REMOTE", "null"),
            new Regel("BB_COUPLER", "PHASE", "null"),
            new Regel("BB_COUPLER", "HYPERLINK", "leer"),
            new Regel("BB_COUPLER", "MAINTENANCE", "null"),
            new Regel("BB_COUPLER", "ALIASNAME", "leer"),
            new Regel("RELAY_OVERCUR", "TYPE", "th", -6),
            new Regel("RELAY_OVERCUR", "DESCRIPTION", "leer"),
            new Regel("RELAY_OVERCUR", "PROJECTED", "null"),
            new Regel("RELAY_OVERCUR", "HYPERLINK", "leer"),
            new Regel("RELAY_OVERCUR", "ALIASNAME", "th", -6),
            new Regel("RELAY_OVERCUR", "MAINTENANCE", "null"),
            new Regel("RELAY_MINMAX_ON_NODE", "TYPE", "th", -6),
            new Regel("RELAY_MINMAX_ON_NODE", "ALIASNAME", "th", -6),
            new Regel("RELAY_MINMAX_ON_NODE", "DESCRIPTION", "leer"),
            new Regel("RELAY_MINMAX_ON_NODE", "PROJECTED", "null"),
            new Regel("RELAY_MINMAX_ON_NODE", "MAINTENANCE", "null"),
            new Regel("RELAY_MINMAX_ON_NODE", "ELEMTYPE", "null"),
            new Regel("RELAY_MINMAX_ON_NODE", "ELEMID", "null"),
            new Regel("RELAY_MINMAX_ON_NODE", "NODEID", "null"),
            new Regel("RELAY_MINMAX_ON_NODE", "VAR", "null"),
            new Regel("RELAY_MINMAX_ON_NODE", "MOD", "null"),
            new Regel("RELAY_MINMAX_ON_NODE", "ACT1", "null"),
            new Regel("RELAY_MINMAX_ON_NODE", "PMS1", "null"),
            new Regel("RELAY_MINMAX_ON_NODE", "PMT1", "null"),
            new Regel("RELAY_MINMAX_ON_NODE", "ACT2", "null"),
            new Regel("RELAY_MINMAX_ON_NODE", "PMS2", "null"),
            new Regel("RELAY_MINMAX_ON_NODE", "PMT2", "null"),
            new Regel("RELAY_MINMAX_ON_NODE", "ACT3", "null"),
            new Regel("RELAY_MINMAX_ON_NODE", "PMS3", "null"),
            new Regel("RELAY_MINMAX_ON_NODE", "PMT3", "null"),
            new Regel("RELAY_MINMAX_ON_NODE", "ACT4", "null"),
            new Regel("RELAY_MINMAX_ON_NODE", "PMS4", "null"),
            new Regel("RELAY_MINMAX_ON_NODE", "PMT4", "null"),
            new Regel("RELAY_MINMAX_ON_NODE", "HYPERLINK", "leer"),
            new Regel("LINE", "TYPE", "th", -8),
            new Regel("LINE", "DESCRIPTION", "th", -7),
            new Regel("LINE", "PROJECTED", "null"),
            new Regel("LINE", "LENGTH", "h", -9, 12, 'd'),
            new Regel("LINE", "INSTALLCOST", "null"),
            new Regel("LINE", "SWITCHABLE", "h", -1, 24, 'i'),
            new Regel("LINE", "UNIT", "null"),
            new Regel("LINE", "R1", "ve", 0, -188, 'd'),
            new Regel("LINE", "X1", "ve", 0, -180, 'd'),
            new Regel("LINE", "G1", "null"),
            new Regel("LINE", "C1", "ve", 0, -164, 'd'),
            new Regel("LINE", "IRMIN", "null"),
            new Regel("LINE", "IRMAX", "ve", 0, -148, 'd'),
            new Regel("LINE", "REDFAK", "h", -1, 24, 'i'),
            new Regel("LINE", "R0", "null"),
            new Regel("LINE", "X0", "null"),
            new Regel("LINE", "C0", "null"),
            new Regel("LINE", "G11", "null"),
            new Regel("LINE", "B11", "null"),
            new Regel("LINE", "G21", "null"),
            new Regel("LINE", "B21", "null"),
            new Regel("LINE", "G10", "null"),
            new Regel("LINE", "B10", "null"),
            new Regel("LINE", "G20", "null"),
            new Regel("LINE", "B20", "null"),
            new Regel("LINE", "SHUNTACTIVE1", "ve", 0, -44, 'd'),
            new Regel("LINE", "SHUNTACTIVE2", "ve", 0, -44, 'd'),
            new Regel("LINE", "Q", "ve", 0, -28, 'd'),
            new Regel("LINE", "CABLE", "ve", 0, -20, 'i'),
            new Regel("LINE", "OVERHEAD", "ve", 0, -16, 'i'),
            new Regel("LINE", "TEMP", "ve", 0, -12, 'd'),
            new Regel("LINE", "FREQDEP", "leer"),   // 0/154
            new Regel("LINE", "NUMPARALLEL", "h", -1, 24, 'i'),
            new Regel("LINE", "MAXOPERT", "he", -11, -144, 'd'),
            new Regel("LINE", "MATERIAL", "h", -11, 106, 'i'),
            new Regel("LINE", "HYPERLINK", "th", -4),
            new Regel("LINE", "IERMAX", "null"),
            new Regel("LINE", "OPERTEMP", "v", 1, 12, 'd'),
            new Regel("LINE", "MAINTENANCE", "null"),
            new Regel("LINE", "YEARINSTALL", "he", -11, -120, 'i'),
            new Regel("LINE", "ALIASNAME", "leer"),   // 0/154
            new Regel("LINE", "IRMID", "null"),
            new Regel("LINE", "UR", "null"),
            new Regel("LINE", "RATEDTEMP", "h", -11, 164, 'd'),
            new Regel("LINE", "LAYOUT", "null"),
            new Regel("LINE", "USEASYMPI", "null"),
            new Regel("LINE", "EMTMODEL", "null"),
            new Regel("LINE", "RETYPE", "leer"),   // 0/154
            new Regel("LINE", "MATCOSTS", "null"),
            new Regel("LINE", "legacy", "th", -4),
        };

        public static readonly Regel[] Abschnitte = new Regel[]
        {
            new Regel("LINESECTIONS", "TYPE", "abt", 0),
            new Regel("LINESECTIONS", "DESCRIPTION", "abt", 2),
            new Regel("LINESECTIONS", "LENGTH", "ab", 0, 0, 'd'),
            new Regel("LINESECTIONS", "INSTALLCOST", "null"),
            new Regel("LINESECTIONS", "UNIT", "null"),
            new Regel("LINESECTIONS", "R1", "ab", 0, 12, 'd'),
            new Regel("LINESECTIONS", "X1", "ab", 0, 20, 'd'),
            new Regel("LINESECTIONS", "G1", "null"),
            new Regel("LINESECTIONS", "C1", "ab", 0, 36, 'd'),
            new Regel("LINESECTIONS", "IRMIN", "null"),
            new Regel("LINESECTIONS", "IRMAX", "ab", 0, 52, 'd'),
            new Regel("LINESECTIONS", "REDFAK", "ab", 0, 60, 'd'),
            new Regel("LINESECTIONS", "R0", "null"),
            new Regel("LINESECTIONS", "X0", "null"),
            new Regel("LINESECTIONS", "C0", "null"),
            new Regel("LINESECTIONS", "Q", "ab", 0, 92, 'd'),
            new Regel("LINESECTIONS", "CABLE", "ab", 0, 100, 'i'),
            new Regel("LINESECTIONS", "OVERHEAD", "ab", 0, 104, 'i'),
            new Regel("LINESECTIONS", "TEMP", "ab", 0, 108, 'd'),
            new Regel("LINESECTIONS", "NUMPARALLEL", "ab", 0, 60, 'd'),
            new Regel("LINESECTIONS", "MAXOPERT", "ab", 0, 108, 'd'),
            new Regel("LINESECTIONS", "MATERIAL", "ab", 1, 12, 'i'),
            new Regel("LINESECTIONS", "IERMAX", "null"),
            new Regel("LINESECTIONS", "OPERTEMP", "ab", 2, 12, 'd'),
            new Regel("LINESECTIONS", "YEARINSTALL", "ab", 2, 20, 'i'),
            new Regel("LINESECTIONS", "IRMID", "null"),
            new Regel("LINESECTIONS", "UR", "null"),
            new Regel("LINESECTIONS", "RATEDTEMP", "null"),
            new Regel("LINESECTIONS", "LAYOUT", "null"),
            new Regel("LINESECTIONS", "CONDITION", "null"),
            new Regel("LINESECTIONS", "SERCOMP", "null"),
            new Regel("LINESECTIONS", "RETYPE", "leer"),
            new Regel("LINESECTIONS", "REIDEAL", "null"),
        };
    }
}
